### ISSUE TITLE
TcpMutex prevents concurrent requests

### ISSUE THREAD

**Issue by nzbart** [Aldaviva/Kasa#15]
When querying multiple devices, some of which may time out, the requests don't happen in parallel. When querying, say 10 devices, this means the total time could be around 300 seconds instead of 30 seconds. This appears to be because there is a global process-wide lock called `TcpMutex`:

https://github.com/Aldaviva/Kasa/blob/0bbc4d4314647a3bffb86982e407c1c9438e2892/Kasa/KasaClient.cs#L21

The TcpClient itself is one-per-instance:

https://github.com/Aldaviva/Kasa/blob/0bbc4d4314647a3bffb86982e407c1c9438e2892/Kasa/KasaClient.cs#L36

Would it be possible to reduce the scope of `TcpMutex` to per-instance rather than per process?

**Comment by Aldaviva** [comment]
Oops that's a great point. I forgot that field was static. Thanks, I will work on this.

**Comment by Aldaviva** [comment]
Should be fixed, feel free to give this a try and let me know if it works for you.

[Kasa.nupkg.zip](https://github.com/Aldaviva/Kasa/files/12825608/Kasa.nupkg.zip) (from [build 25](https://github.com/Aldaviva/Kasa/actions/runs/6425645526))

**Comment by nzbart** [comment]
@Aldaviva thanks for getting onto this so quickly! I've tested version 1.0.1, and the fix appears to work as expected.

**Comment by Aldaviva** [comment]
You're welcome!

Published to NuGet Gallery as version [1.0.1](https://www.nuget.org/packages/Kasa/1.0.1).
